#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BikeShop;
    using BikeShop.Domain;
    using BikeShop.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Product>>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Home Page";

            
            #line default
            #line hidden
WriteLiteral("\r\n<main");

WriteLiteral(" class=\"container\"");

WriteLiteral(" ng-app=\"productsViewer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" ng-controller=\"mainProductsController\"");

WriteLiteral(">\r\n        <div>\r\n");

WriteLiteral("            ");

            
            #line 9 "..\..\Views\Home\Index.cshtml"
       Write(Html.ActionLink("Create Bike", "CreateProduct"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        {{searchTerm}}\r\n        <form");

WriteLiteral(" name=\"searchUser\"");

WriteLiteral(" ng-click=\"searchButtonClicked()\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label>Search</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" required");

WriteLiteral(" id=\"txtSearch\"");

WriteLiteral(" placeholder=\"Search...\"");

WriteLiteral(" ng-model=\"searchTerm\"");

WriteLiteral(" />\r\n            </div>\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral("  value=\"Search\"");

WriteLiteral("/> \r\n        </form>\r\n        <div>\r\n            <div");

WriteLiteral(" ng-repeat=\"product in products\"");

WriteLiteral("> {{product}} </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"has-error\"");

WriteLiteral(">{{error}}</div>\r\n    </div>\r\n</main>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"https://code.angularjs.org/1.6.8/angular.js\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 956), Tuple.Create("\"", 993)
, Tuple.Create(Tuple.Create("", 962), Tuple.Create<System.Object, System.Int32>(Href("~/App/MainProductsController.js")
, 962), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
